name: ğŸ”„ CI-CD

on:
  push:
  workflow_dispatch:

concurrency:
  group: 'CI-CD - ${{ github.workflow }} @ ${{ github.ref_name }}'
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write
  pull-requests: read
  packages: write

jobs:
#  ci:
#    name: ğŸ› ï¸ CI
#    uses: sidkos/metadata_server/.github/workflows/ci.yml@main
#    secrets: inherit

  build-server-image:
    name: ğŸ—ï¸ ğŸ–¼ï¸ Build Server Docker Image
#    needs: ci
    uses: sidkos/metadata_server/.github/workflows/build_docker_image_store_in_github.yml@main
    with:
      file: "Dockerfile"
      image_name: "metadata_server"
    secrets: inherit

  build-openapi-client:
    name: ğŸ ğŸ“¦ Build OpenAPI Client and store artifacts
#    needs: ci
    uses: sidkos/metadata_server/.github/workflows/build_openapi_client_store_in_github.yml@main
    with:
      open_api_spec_file: "src/open_api_spec.yml"
    secrets: inherit
