name: ğŸ”„ CI-CD

on:
  push:
  workflow_dispatch:

concurrency:
  group: 'CI-CD - ${{ github.workflow }} @ ${{ github.ref_name }}'
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write
  pull-requests: read
  packages: write

jobs:
  ci:
    name: ğŸ› ï¸ CI
    uses: sidkos/metadata_server/.github/workflows/ci.yml@main
    secrets: inherit

  build-server-image:
    name: ğŸ—ï¸ ğŸ–¼ï¸ Build Server Docker Image
    needs: ci
    uses: sidkos/metadata_server/.github/workflows/build_docker_image.yml@main
    with:
      file: "Dockerfile"
      image_name: "metadata_server"
    secrets: inherit

  component-tests:
    name: ğŸ§© ğŸ” Component Tests
    needs: build-server-image
    uses: sidkos/metadata_server/.github/workflows/component_tests.yml@main
    with:
      image_name: "metadata_server"
      image_tag: "latest"
      tests_path: "./tests/component"
      tests_command: "pytest"
      build_and_install_script: "./scripts/build_and_install_dp_client.sh"
    secrets: inherit
